### ISSUE TITLE
Bug with EOL processing

### ISSUE THREAD

**Issue by AlexBlade** [nadar/quill-delta-parser#12]
**Bug description**
Accordingly to **[deltas](https://quilljs.com/guides/designing-the-delta-format/)** description the EOL character can be only **\n**, but in Windows PHP_EOL is equal to **\r\n**. Due to this issue the method _replaceNewlineWithExpression_ of the _Lexer_ class will not work correctly.
```
protected function replaceNewlineWithExpression($string)
{
   return str_replace(PHP_EOL, self::NEWLINE_EXPRESSION, $string);
}
```
**Example of a delta-object**
```
{
  "ops": [
    {
      "insert": "Header 1"
    },
    {
      "attributes": {
        "header": 5
      },
      "insert": "\n"
    },
    {
      "insert": "Some cool stuff\nHeader 2"
    },
    {
      "attributes": {
        "header": 3
      },
      "insert": "\n"
    }
  ]
}
```

**Produced HTML (incorrect)**
```
<h5>Header 1</h5><h3>Some cool stuff Header 2</h3>
```

**The expected html output the delta should produce**
```
<h5>Header 1</h5><p>Some cool stuff</p><h3>Header 2</h3>
```

**Expected behavior (Bugfix sugestion)**

```
class Lexer
{
    const EOL = "\n";
    ...

    protected function replaceNewlineWithExpression($string)
    {
        return str_replace(self::EOL, self::NEWLINE_EXPRESSION, $string);
    }
...
```

**Additional context**
Thanks a lot for your work :)

**Comment by nadar** [comment]
good catch! thanks. indeed you are right, it wont work on windows.I will update the code and release a patch.

**Comment by AlexBlade** [comment]
Thanks for fast bugfixing :)
