### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by bogusred** [nadar/quill-delta-parser#14]
Hello nadar and lode,
I'm interested in using this package but there is no license information so I can't use it until I know what the license terms are. Can you please provide a license?
Thanks for writing this!

**Comment by nadar** [comment]
Indeed, i will add MIT license. Thanks for the hint.

**Comment by nadar** [comment]
https://github.com/nadar/quill-delta-parser/blob/master/LICENSE.md

**Comment by bogusred** [comment]
Sweet. Thank you @nadar !
