### ISSUE TITLE
Rendering inline listeners priority

### ISSUE THREAD

**Issue by jwissels** [nadar/quill-delta-parser#16]
**Describe the bug**
When rendering inline items the priority messes with the content, sometimes even deleting content

**The delta code which generates the Problem**
```
{"ops": [
  {"attributes": {"italic": true},"insert": "italic text"},
  {"attributes": {"link": "https://www.test.com/","bold": true},"insert": "link"},
  {"insert": "\n"}
]}
```
**The expected html output the delta should produce**
```
<p><em>italic text</em><a href="https://www.test.com/" target="_blank"><strong>link</strong></a></p>
```

**Expected behavior**
I expect the order of the inserts to be honored

**Additional context**
This bug also happens with other inline items;
I would like to help fix it but am unsure of the desired direction; It feels like we need to revisit the entire order of how inline things are rendered at the moment. Did you notice this before? Do you have a desired direction? Or do you consider this behavior as intended?

If you update output.php on line 40 & 41
```
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
```
link will work on the demo page

**Comment by nadar** [comment]
What do you get instead of `<p><em>italic text</em><a href="https://www.test.com/" target="_blank"><strong>link</strong></a></p>`?

```
If you update output.php on line 40 & 41

<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
link will work on the demo page
```

What do you mean with this? Mabye create another issues which takes care of this.

**Comment by jwissels** [comment]
Expected output : 
```
<p><em>italic text</em><a href="https://www.test.com/" target="_blank"><strong>link</strong></a></p>
```

Actual output : 
```
<p><a href="https://www.test.com/" target="_blank"><strong>link</strong></a><em>italic text</em></p>
```

**Comment by jwissels** [comment]
And even simpler : 
```
{"ops": [
  {"attributes": {"italic": true},"insert": "italic"},
  {"attributes": {"bold": true},"insert": "bold"},
  {"insert": "\n"}
]}
```
expected : 
`<p><em>italic</em><strong>bold</strong></p>`
actual : 
`<p><strong>bold</strong><em>italic</em></p>`

**Comment by nadar** [comment]
I will do some tests. Thanks for the report.

**Comment by nadar** [comment]
yes indeed i can confirm this bug. And its because the bold inline element renders before the italic element. I will do some tests.
