### ISSUE TITLE
Font attribute causes insert to be skipped

### ISSUE THREAD

**Issue by gfaugere** [nadar/quill-delta-parser#23]
Insert with "`font`" attribute appear to be skipped when rendering.   
This is probably related to #20 but `font` being a native Quill feature, I did not expect this.

Delta:
```
{"ops":[{"insert":"Lorem "},{"attributes":{"font":"serif"},"insert":"Ipsum"},{"insert":" Dolor. "},{"attributes":{"font":"monospace"},"insert":"Sit"},{"insert":" Amet.\n"}]}
```
Expected output (not sure how the `span` should be styled):
```
<p>Lorem <span style="font-family: serif;">Ipsum</span> Dolor. <span style="font-family: monospace;">Sit</span> Amet.</p>
```
Output received:
```
<p>Lorem </p><p> Dolor. </p><p> Amet.</p>
```

**Comment by nadar** [comment]
Hey @gfaugere 

Thanks for the report. Indeed the inline element "font" is not done yet, i will do it asap - should take not to much time as its similar to other inline elements.
