### ISSUE TITLE
Inserting an empty line in header 2 format creates strange html

### ISSUE THREAD

**Issue by stijnster** [nadar/quill-delta-parser#25]
Hi there,

thanks for your work on this parser, I've started to use it a few weeks ago and extended it with success!

However, we noticed one thing when parsing the delta to HTML.

For this ticket I'll add some simplified content.

![Screenshot 2019-08-28 at 19 01 31](https://user-images.githubusercontent.com/27271/63876741-711dd980-c9c6-11e9-92bd-e1f2a668abd6.png)

This gets converted into the following delta;
```
{"ops":[{"insert":"Here is a title"},{"attributes":{"header":2},"insert":"\n"},{"insert":"Here is some content\n"}]}
```
And generates just fine.

However, when we hit enter just before "Here is a Title" in the quill.js editor, an empty h2 line is inserted which generates the following delta;
```
{"ops":[{"attributes":{"header":2},"insert":"\n"},{"insert":"Here is a title"},{"attributes":{"header":2},"insert":"\n"},{"insert":"Here is some content\n"}]}
```
This should generate something like the following (we can debate wether the <br> should be there or not, or find another solution);
```
<h2><br>Title</h2>
<p>Here is some content</p>
```
Instead it generates something like;
```
<h2>Here is a titleHere is some content</h2><h2>Here is a title</h2>
```
At first, this example might seem far fetched. But in the editor it is easy to do and easy to overlook the fact that the empty line is still in "header2";

![Screenshot 2019-08-28 at 19 01 39](https://user-images.githubusercontent.com/27271/63876779-87c43080-c9c6-11e9-8866-64b139f777e3.png)

Thanks for taking the time to have a look a this issue!

Kind regards,

Stijn

**Comment by nadar** [comment]
So the problem appears if you press "shift+enter"?

**Comment by stijnster** [comment]
No, just a regular enter a the beginning of the phrase "Here is a title". This inserts an empty header 2 above that one.

**Comment by nadar** [comment]
I will do some research, thanks for the report.

**Comment by stijnster** [comment]
Great! Thanks, let me know if you need more information!

**Comment by nadar** [comment]
I just saw that the enter you made has "Heading 2" and "link" icon activated? Are you using latest version of quill editor (js)?

**Comment by nadar** [comment]
<img width="272" alt="Bildschirmfoto 2019-08-28 um 19 17 08" src="https://user-images.githubusercontent.com/3417221/63877765-83007c00-c9c8-11e9-8a57-5f8702ce9f49.png">

**Comment by stijnster** [comment]
We're on 1.3.6, so I think that's the latest version. I had the screenshot made while the mouse was hovering over the link button. Here is an updated screenshot.

![Screenshot 2019-08-28 at 19 19 27](https://user-images.githubusercontent.com/27271/63877944-da065100-c9c8-11e9-8273-676c10f568fe.png)

**Comment by pinkminds** [comment]
We're having a similar issue. Whenever a title tag has no real text content (for example reproducible by adding an enter in front of a H2) the text below gets scrambled upon save.

**Comment by nadar** [comment]
then we should fix it asap. someone suggestions or would lile to send a PR?

**Comment by nadar** [comment]
If this is the json

```json
{
    "ops": [
        {
            "attributes": {
                "header": 2
            },
            "insert": "\n"
        },
        {
            "insert": "foobar"
        },
        {
            "attributes": {
                "header": 2
            },
            "insert": "\n"
        },
        {
            "insert": "text\n"
        }
    ]
}
```

i would say the only correct rendering would be:

```html
<h2></h2>
<h2>foobar</h2>
<p>text</p>
```

@pinkminds @stijnster do you agree on this?

**Comment by stijnster** [comment]
Totally agree!

**Comment by nadar** [comment]
Take a look at the PR#26 (https://github.com/nadar/quill-delta-parser/pull/26). You could also always create an issue if you find problems or if elements are missing. let me know if i can help

**Comment by pinkminds** [comment]
👍
