### ISSUE TITLE
Random line breaks

### ISSUE THREAD

**Issue by Sander00** [nadar/quill-delta-parser#3]
I am using this package after using @deanblackborough's first, because I needed the ability to extend.

The only problem I am having is that the line breaks are 3 lines. Whenever I have a break in my delta, it shows as `<p><br></p>`. I wasn't having this issue with the other package. Do you have any idea what causes this?

thanks!

**Comment by nadar** [comment]
Or just the part which bring's up the Problem?

Von meinem Mobiltelefon gesendet.

Sander <notifications@github.com> schrieb am Do., 25. Okt. 2018, 13:26:

**Comment by Sander00** [comment]
`{"ops":[{"insert":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua:\n        \nLorem ipsum dolor sit amet, consectetur adipiscing elit, Lorem ipsum dolor sit amet, consectetur adipiscing elit, Lorem ipsum dolor sit amet, consectetur adipiscing elit."},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"Lorem ipsum dolor sit amet, consectetur adipiscing elit."},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"Lorem ipsum dolor sit amet, consectetur adipiscing elit."},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"Lorem ipsum dolor sit amet, consectetur adipiscing elit"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"\n"},{"attributes":{"bold":true},"insert":"Lorem ipsum dolor sit amet, consectetur adipiscing elit?"},{"insert":"\nLorem ipsum dolor sit amet, consectetur adipiscing elit:\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit;"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"Lorem ipsum dolor sit amet, consectetur adipiscing elit;"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"Lorem ipsum dolor sit amet, consectetur adipiscing elit)."},{"attributes":{"list":"bullet"},"insert":"\n"}]}`

**Comment by nadar** [comment]
Perfect. Would also be so kind to provide me the expected output, so i am much faster writting the unit tests. Thank you!

**Comment by Sander00** [comment]
Got:
![](https://i.imgur.com/sKTMOiE.png)

Expected:
![](https://i.imgur.com/gK17cDX.png)

**Comment by nadar** [comment]
So the problem could be those whitespaces? `\n        \nLorem`

**Comment by Sander00** [comment]
Here is another one: 

With the other package I get this:
![](https://i.imgur.com/6Ao5l7S.png)

And with yours:
![](https://i.imgur.com/lND03Lx.png)

The delta is: 
`{"ops":[{"insert":"De AOW-pensioenleeftijd gaat geleidelijk naar 67 jaar in 2021. Vanaf 2022 hangt de AOW-leeftijd af van de levensverwachting. Zie voor de hoogte van de pensioenleeftijd de "},{"attributes":{"link":"https://www.svb.nl/int/nl/aow/wat_is_de_aow/wanneer_aow/index.jsp"},"insert":"website"},{"insert":" van de Sociale Verzekeringsbank. Inmiddels is de AOW-pensioenleeftijd voor mensen geboren na 30 september 1956 vastgesteld op 67 jaar en 3 maanden. De verwachting is dat pensioenregelingen deze verhoging van de AOW-pensioenleeftijd zullen volgen.\n\nDe pensioenregelingen worden in de komende jaren (na overleg tussen de betrokken partijen) aangepast. Zowel de opbouw (premie) als de pensioenleeftijd zullen worden bijgesteld.\n\nAls iemand eerder met pensioen wil dan de datum waarop zijn AOW-pensioen ingaat, moet hij het inkomensgat dat zo ontstaat, zelf opvullen. Dat kan door het inzetten van spaargeld of l"},{"attributes":{"underline":true},"insert":"evenslooptegoed"},{"insert":". Ook kan hij zijn aanvullend pensioen eerder laten ingaan. Als hij dit doet, zal zijn pensioen per jaar wel lager uitkomen. Dit komt omdat het beschikbare pensioen over de verwachte levensjaren wordt gespreid.\n\nTot 1 januari 2018 was er een werkbonus voor werknemers van 61 tot 65 jaar (peildatum 31 december 2014). De bonus is maximaal voor mensen met een minimuminkomen. Door het inzetten van de bonus konden mensen met lagere inkomens eerder met pensioen dan op hun AOW-leeftijd. \n"}]}`

**Comment by nadar** [comment]
It would be intresting to see how this delta code looks inside the quill editor in order to ensure which is the correct output. Because the above example produces `volgen.\n\nDe` - which indicates indeed an empty `<p><br /></p>`

So this example for quill official playground (https://quilljs.com/docs/delta/)

<img width="1105" alt="bildschirmfoto 2018-10-25 um 14 04 05" src="https://user-images.githubusercontent.com/3417221/47498951-0314fd00-d85f-11e8-9533-37df282e38bd.png">

So, i am also still researching with you, but maybe the other editor made it wrong, but it looks good on your website, but it was wrong by definition. But not sure yet

**Comment by Sander00** [comment]
Looks normal in the editor too. 

![](https://i.imgur.com/evLqsB1.png)

**Comment by nadar** [comment]
![image](https://user-images.githubusercontent.com/3417221/47501449-db756300-d865-11e8-85af-a4b0b4700b55.png)

Please take a look at the screenshot i just uploaded above.

1. For me it looks like that we are producing the same output as quill does, with an empty `<p><br /></p>` for "newlines which are empty".
2. If you would store the html output from quill, this is what you would get.
3. So maybe its just a question of styling?

**Comment by nadar** [comment]
@Sander00 i also did a test on @deanblackborough parser:

(https://transmute-coffee.com/php-quill-renderer.php#demo)

<img width="762" alt="bildschirmfoto 2018-10-25 um 19 36 00" src="https://user-images.githubusercontent.com/3417221/47519186-471ef680-d88d-11e8-97a5-f7f4846157af.png">

Maybe its an old version, but this output looks wrong to me?

**Comment by deanblackborough** [comment]
Obviously, I don't want to get involved here as this is @nadar's library, however, as mine was mentioned I thought I would pop in, that is currently broken in the latest version, I'm working on it right now and it will be fixed when v3.14.3 is released, not sure how something so obvious got past testing.

**Comment by deanblackborough** [comment]
FYI, 3.14.3 is out and the issue @nadar spotted is fixed.

**Comment by nadar** [comment]
Thanks for jumping in :-)

And now i see also the "problem" of @Sander00 - because @deanblackborough library parsers the quill different, to what quill would parser the html itself. In the screenshot below you can see how i am inspecting the html of the quill editor (lets call it the raw html output of quill):

Quill makes:

```html
<p>foo</p>
<p>bar</p>
<p><br /></p>
<p>barfoo</p>
```

But the @deanblackborough makes:

```
<p>foo<br />
bar</p>
<p>barfoo</p>
```

<img width="707" alt="bildschirmfoto 2018-10-25 um 23 58 17" src="https://user-images.githubusercontent.com/3417221/47532974-2d43da80-d8b2-11e8-9213-76fdaf343dd3.png">

My parser try's to generate exactly the same html then the quill "raw html saving format" would do as well. (instead of using deltas, you can also directly save the html) This is what i use as reference in all my unit tests.

**Comment by nadar** [comment]
I am going to close this @Sander00 as this is an expected behavior along with was quill delta html produces.

**Comment by mikepictor** [comment]
I wanted to add a comment (I know this is closed), though maybe I will find a better thread, but I am getting this with the quill editor. The following is a screenshot of a sandbox test environment we have. If I have text before a bulleted list, quill adds in an extra <p><br></p> before the bulleted list. It's not there in the parsed html from the editor, but when that html is passed into a new read only editor, the extra line is added in. This sounds too similar to this thread.

![base_ui_showcase](https://user-images.githubusercontent.com/4552747/52594085-9a0ac280-2e18-11e9-9721-c039110e014e.png)

**Comment by nadar** [comment]
@mikepictor what parser are you using to render the view?

**Comment by mikepictor** [comment]
Sorry, when I found this thread, I thought it was about the quill editor itself. It's not, is it? Ultimately, I don't know the answer to your question. I'm just implementing the quill editor component, I don't know enough about it under the hood, and I don't understand what role quill data parsers play in use of the editor. We haven't defined any specific parser that I know about.

Sorry...this may have nothing to do with you, it's just that the symptom seemed so similar that it felt like it must be relevant.

**Comment by nadar** [comment]
You are welcome, even i assume this library has nothing to do with your problem, unless you are rendering the quill deltas with my quill delta parser library :-)

1. The quill editor can produce a delta format - which allows you to store the input data (html from wysiwyg) as json => https://quilljs.com/docs/delta/
2. How is the "Viewer" section of your screenshot generated? So maybe if you have more information i can point you in the right direction.
3. This is the official quill repository: https://github.com/quilljs/quill

**Comment by mikepictor** [comment]
1-at least the way we use it..it just produces html, and we're storing the html
2-It's just another editor in read only mode, with the same html passed back in
3-yeah, thanks. Odds are this isn't your problem.
