### ISSUE TITLE
Issue with multiple ul-li lists where ul-li list contains only one item

### ISSUE THREAD

**Issue by stijnster** [nadar/quill-delta-parser#30]
Hi there,

we found a new issue when using the quill-delta-parser;

<img width="621" alt="Screenshot 2019-10-23 at 15 15 23" src="https://user-images.githubusercontent.com/27271/67396599-283e6780-f5a8-11e9-99a4-a3b572d55061.png">

Here is the initial delta;

```
{"ops":[{"insert":"line 1\nbullet 1 - 1"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"line 2\nbullet 2 - 1"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"line 3\nbullet 3 - 1"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"line 4\nbullet 4 - 1"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"bullet 4 - 2"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"line 5\n"}]}
```

And here is the current output;

```
<p>line 1</p><ul><li>bullet 1 - 1</li></ul><p>line 2</p><li>bullet 2 - 1</li><p>line 3</p><li>bullet 3 - 1</li><p>line 4</p><ul><li>bullet 4 - 1</li><li>bullet 4 - 2</li></ul><p>line 5</p>
```

However, this is the expected output;

```
<p>line 1</p><ul><li>bullet 1 - 1</li></ul><p>line 2</p><ul><li>bullet 2 - 1</li></ul><p>line 3</p><ul><li>bullet 3 - 1</li></ul><p>line 4</p><ul><li>bullet 4 - 1</li><li>bullet 4 - 2</li></ul><p>line 5</p>
```

The ul-li lists with only one item are missing the wrapping ul element, except for the very first one (bullet 1 - 1). Strangely enough, the last bullet list (with more than one item) is created as expected.

I've started looking into the `listsener\Lists` class to see if I could fix the problem. But it turns out to be quite an adventure :)

**Comment by nadar** [comment]
thanks, i will make a unit test asap in order to see what the problem is.

**Comment by stijnster** [comment]
@nadar Would you mind having a look at https://github.com/stijnster/quill-delta-parser/commit/c0b9fcacdc07cf36261947fb645865c02ce5af54?

I wrote a test case for the example above. Then I've simplified the code to insert an ul/ol tag when there is none and it makes all tests pass.

Either there are not enough tests to cover all situations, or this solves the problem :)

**Comment by nadar** [comment]
So please create a pull request, so we can take a closer look. thanks!
