### ISSUE TITLE
Center and Header

### ISSUE THREAD

**Issue by Nevercold** [nadar/quill-delta-parser#34]
**Describe the bug**
When i change Header and set it center, the header will not set. (<h1*></h1*> => <p*></p*>)

**The delta code which generates the Problem**

```
{"ops":[{"insert":"test"},{"attributes":{"align":"center","header":1},"insert":"\n"}]}
```

**The expected html output the delta should produce**

```
<p class="ql-align-center">test</p>
```

**Comment by Nevercold** [comment]
I think one overrides the other. So if both are set, the 2nd overwrites the first

**Comment by nadar** [comment]
Hey @Nevercold, i am going to make some tests. But in general i think headings should not be centered, even though the editor might allow this. 

> The expected html output the delta should produce
> `<p class="ql-align-center">test</p>`

I would expect: <h1><center>test</center></h1> or <h1 style="text-align:center;">test</h1>?

**Comment by Nevercold** [comment]
you can make it always expand. e.g. if you only do center it is `<center> </center>` and if you also make header1 `<h1><center></center> </h1>`. I think that's the easiest to implement.Do you add it? I myself am not so good at doing it myself. I need it for my Website.

**Comment by Nevercold** [comment]
when is this "fixed"? I myself can't do it: /

**Comment by nadar** [comment]
i need to take more time, i took a quick look yesterday, but its more complicated then expected because there is aready an align item which generates paragraphes, which might be wrong. it should be an inline element. Maybe i will have some time today or tomorrow, i'll let you know. What does your quill editor config looks like?

**Comment by Nevercold** [comment]
Okay. 
Which config do you mean?

**Comment by nadar** [comment]
I was talking about the editor config, but i already could setup the align button. 

I see now the problem with align propertie, it applies on the current blocks, i think i know how to fix it.

**Comment by Nevercold** [comment]
nice! 
is it fixed? I see, the pull request check is failed

**Comment by Nevercold** [comment]
@nadar

**Comment by nadar** [comment]
I see notifications, its an open source project, everyone does it for free. If you like to to sponsor and help you can click the sponsors badge on the repo.

<img width="117" alt="Bildschirmfoto 2019-12-21 um 20 11 38" src="https://user-images.githubusercontent.com/3417221/71312703-20773400-242e-11ea-8bd0-7f296b2eed2d.png">
