### ISSUE TITLE
Object of class PhpParser\Lexer could not be converted to string

### ISSUE THREAD

**Issue by snake-py** [nadar/quill-delta-parser#40]
Hello,
I am getting undefined method when I am trying to call render:

        $lexer = new Lexer(json_decode($delta, true));
        echo $lexer->render();
        return;

**The delta code which generates the Problem**

Example:
```
{"ops":[{"insert":"this is a test\n"}]}
```

**The expected html output the delta should produce**

Example:

```
<p>This is a test</p>
```

**Expected behavior**
It should simply render

**Comment by nadar** [comment]
could please send me the full stack trace? But maybe just return your value instead of echoing

return $lexer->render()

**Comment by snake-py** [comment]
Sorry I just saw my issue here. Very stupid of me it used the wrong Lexer class, this is why.
