### ISSUE TITLE
Best practice for overriding Link class

### ISSUE THREAD

**Issue by njtmead** [nadar/quill-delta-parser#46]
I am looking for a way to customise link behaviour:

external links:
rel = "nofollow"
target = "_blank"

internal links:
rel = ""
target = ""

I'm just wondering what is the best way to override the existing Link class behaviour?

I see in the docs how to override the wrapper property, but is there a way to override the process method?

If not and I need to create another class CustomLink and register it, will both Link and CustomLink be run?

Am I maybe better off just doing a composer override of the Link.php file completely and change the process method this way?

Thanks for your help and for creating this package.

**Comment by nadar** [comment]
Hi @njtmead 

Is there a way to determine whether its an internal or external link in quill? If yes, what would the quill json look like?

What we could do for sure is to check whether the link is relative or not (`/about/me` - seems to be internal, `https://luya.io` - seems to be external) but i think this won't help a lot? 

> If not and I need to create another class CustomLink and register it, will both Link and CustomLink be run?

You could just override `Link.php` with your own class as explained, or why would you like to have both? 

> Am I maybe better off just doing a composer override of the Link.php file completely and change the process method this way?

I would not recommend this solution.

**Comment by nadar** [comment]
I am going to close this issue because:

- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.
