### ISSUE TITLE
Wrong parsing

### ISSUE THREAD

**Issue by gilsdav** [nadar/quill-delta-parser#47]
**Describe the bug**

Code generated bu Quill and understaded by quill is totaly broken using this library.

Easily reproductible by using multiple headers in same editor.

**The delta code which generates the Problem**

Example:
```
{"ops":[{"insert":"title 1"},{"attributes":{"header":1},"insert":"\n"},{"insert":"\nhelllooook\n\nthe title two"},{"attributes":{"header":2},"insert":"\n"},{"insert":"\nok ok\n"}]}
```

**The expected html output the delta should produce**

```html
<h1>title 1</h1>
<p>helllooook</p>
<h2>the title two</h2>
<p>ok ok</p>
```

![image](https://user-images.githubusercontent.com/21348530/112386025-a00a4780-8cf0-11eb-93ff-ba2decc678e0.png)

**Comment by nadar** [comment]
What html output is generated instead?

**Comment by gilsdav** [comment]
I'm very sorry, I found the issue and it comes from me (sanitatize that removes "\" before each "n". With it, it does the job. Thank you ! :)

**Comment by nadar** [comment]
glad to hear :-)
