### ISSUE TITLE
Image wrapped in italics renders as text instead of showing the image

### ISSUE THREAD

**Issue by njtmead** [nadar/quill-delta-parser#51]
**Describe the bug**

Insert an image to quilljs editor.
Select all (ctrl + a).
Click "italic" icon from quill toolbar.
(my users do this often to italicise their text but inadvertently wrap the image also)

**The delta code which generates the Problem**

Example:
```
{"ops":[{"attributes":{"italic":true},"insert":{"image":"https://d3i7mhpybxyfiq.cloudfront.net/original/3xqr7oi10dt67v6zc1e2lv.jpg"}},{"insert":"\n"}]}
```

**The expected html output the delta should produce**

anything that creates the img object rather than rendering as text. don't mind where the italic `<em>` tags end up though they should probably logically wrap the img in this example delta.

Example:

```
<p><em><img src="https://d3i7mhpybxyfiq.cloudfront.net/original/3xqr7oi10dt67v6zc1e2lv.jpg"></em></p>
```

**What html output the delta is producing instead**

Example:

```
<p><em>{"image":"https:\/\/d3i7mhpybxyfiq.cloudfront.net\/original\/3xqr7oi10dt67v6zc1e2lv.jpg"}</em></p>
```

**Comment by nadar** [comment]
HI @njtmead Just to understand correctly from our output: The image is not even rendered as img tag, instead its `<p><em>{"image":"https:\/\/d3i7mhpybxyfiq.cloudfront.net\/original\/3xqr7oi10dt67v6zc1e2lv.jpg"}</em></p>`? I will check that, thanks for the report!

**Comment by njtmead** [comment]
That's correct yes, the image is not being rendered and just showing text instead. Thanks for looking into this.
