### ISSUE TITLE
Heading level nested in attributes results in fatal error

### ISSUE THREAD

**Issue by linc** [nadar/quill-delta-parser#57]
I'm parsing a delta from Vanilla Forums (also referenced in #53). Some posts contain this (or similar) Delta entry for a heading:

`{"attributes":{"header":{"level":1,"ref":""}},"insert":"\n"}`

This results in the errors:

> Warning: Array to string conversion in /Users/linc/code/porter/vendor/nadar/quill-delta-parser/src/listener/Heading.php on line 46

> Fatal error: Uncaught Exception: An unknown heading level "Array" has been detected. in /Users/linc/code/porter/vendor/nadar/quill-delta-parser/src/listener/Heading.php:46

In the Quill JS docs, I only see `header` used like this:

`{ insert: '\n', attributes: { header: 1 } },`

This appears to be what line 46 in Heading.php is expecting — an integer value to insert, not an array with a `level` element inside it.

I do not know if this is something Vanilla Forums customized or is now part of the official Quill Delta format, but I thought I'd report it in case it's something you want to support.

**Comment by linc** [comment]
If anyone else runs into this issue, I wrote a quick pre-processor to fix the data before it hits the lexer:

    /**
     * Vanilla appears to use a customized 'header' element in Quill Deltas that breaks parsers.
     *
     * @param string $text
     * @return string
     */
    function fixQuillHeaders(string $text): string
    {
        // Avoid regex if we can.
        if (strstr($text, '{"header"') === false) {
            return $text;
        }

        // Remove array of attributes under `header` and simply give the numeric level instead.
        // ex: {"header":{"level":1,"ref":""}},
        return preg_replace('/{"header":{"level":([1-6]),"ref":"\w*"}}/', '{"header":$1}', $text);
    }

**Comment by nadar** [comment]
Hi @linc, thanks for the report. 

So to summarize: Vanilla Forums generates:

```
{"attributes":{"header":{"level":1,"ref":""}}}
```

but quill generally generates

```
{"attributes": { "header": 1 }
```

I quickly searched for [changelog](https://github.com/quilljs/delta/blob/main/CHANGELOG.md) in quill and could not find anything - maybe i was at the wrong changelog anyhow. Maybe vanilla forum has generate its own elements, which then generate the above quill delta code.

It would be interesting to know if all vanilla forums generate that "wrong" code. So we could just provide a VanillaForumsHeadingListener which you can use to [override](https://github.com/nadar/quill-delta-parser#override-built-in-listeners) the default heading listener.

**Comment by linc** [comment]
@nadar Yeah it's definitely baked into core for Vanilla. I couldn't tell you exactly when i twas added, but I'd guess quite early in the deployment of Quill. I was the former DoE there.

**Comment by nadar** [comment]
So is there something i can further do for you @linc or can we close that issue?
