### ISSUE TITLE
Nested lists are not rendered as nested

### ISSUE THREAD

**Issue by utdrmac** [nadar/quill-delta-parser#74]
**Describe the bug**
Nested lists are not rendered as nested.

**The delta code which generates the Problem**

```
{"ops":[{"insert":"Level 1A"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"Level 2A"},{"attributes":{"indent":1,"list":"bullet"},"insert":"\n"},{"insert":"Level 2B"},{"attributes":{"indent":1,"list":"bullet"},"insert":"\n"},{"insert":"Level 1B"},{"attributes":{"list":"bullet"},"insert":"\n"}]}
```

**The expected html output the delta should produce**

```
<ul><li>Level 1A<ul><li>Level 2A</li><li>Level 2B</li></ul></li><li>Level 1B</li></ul>
```

**Expected behavior**
The expected behavior is to render nested lists

**Screenshots**
Editor: <img width="555" alt="Screen Shot 2022-10-31 at 3 18 45 PM" src="https://user-images.githubusercontent.com/4413670/199102581-cd2991e7-0085-4c46-b6ab-223ddf018d8f.png">

Rendered with nadar: <img width="282" alt="Screen Shot 2022-10-31 at 3 18 53 PM" src="https://user-images.githubusercontent.com/4413670/199102584-c3488a74-44d4-433a-bee9-5ba0fa778e92.png">

**Additional context**
DBlackborough sent me to this QuillJS render library because I needed support for nested lists and his didn't support it. I thought he was implying this library did support them.

**Comment by nadar** [comment]
@utdrmac can you please try the branch quickly in your project? Just replace in your composer.json

```
"nadar/quill-delta-parser": "^3.0"
```

with

```
"nadar/quill-delta-parser": "dev-issue-74 as 3.2.0"
```

and run `composer update`

**Comment by utdrmac** [comment]
Holy crap man! That was a fast turnaround! See my editor and the renderer below:

<img width="501" alt="Screen Shot 2022-11-01 at 8 14 42 AM" src="https://user-images.githubusercontent.com/4413670/199241821-5f8667a9-7bd6-434b-ad28-39db903f46ee.png">
<img width="297" alt="Screen Shot 2022-11-01 at 8 14 47 AM" src="https://user-images.githubusercontent.com/4413670/199241824-42b0cdca-b471-4ea1-aaf7-1f6fc1054ac0.png">

**Comment by nadar** [comment]
@utdrmac https://github.com/nadar/quill-delta-parser/releases/tag/3.2.1

**Comment by deanblackborough** [comment]
@nadar has been on a roll with this package so I just assumed he already supported nested lists, guess he does now :) I might have to retire mine soon, just don’t seem to have the time.

**Comment by nadar** [comment]
Hi @deanblackborough afaik [the quill editor is dead](https://github.com/quilljs/quill/issues/3359) anyhow and the quill delta format is also something i wish i would never have discovered, it just makes no sense at all 😄

**Comment by utdrmac** [comment]
@nadar Oh seriously?! quilljs is dead? Damn. I just discovered it last week and spent the weekend moving off TinyMCE. I'm sorry I bothered you with this request for something that isn't in development anymore. Any recommendations for an alternative?

**Comment by nadar** [comment]
Well, choose quill over TinyMCE might be still a good migration 😄 👍  I would recommend: https://tiptap.dev/

>  I'm sorry I bothered you with this request for something that isn't in development anymore.

No problem, its good to have featured of nested lists. There are still a lot of people using quill, i would say the editor is not bad, runs stable, but afaik there will be no version 2.0, even [they announced that back in 2017](https://quilljs.com/blog/).
