### ISSUE TITLE
Having an empty list breaks the rendering

### ISSUE THREAD

**Issue by psociety** [nadar/quill-delta-parser#78]
Ty for creating this delta parser!!!

**Describe the bug**
Having an empty list breaks the rendering.

**The delta code which generates the Problem**

```json
[
  {
    "insert": "HI THERE",
    "attributes": {
      "bold": true,
      "color": "#000000",
      "background": "transparent"
    }
  },
  {
    "insert": "\n",
    "attributes": {
      "align": "center"
    }
  },
  {
    "insert": "\nIn publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before final copy. "
  },
  {
    "insert": "\n",
    "attributes": {
      "align": "justify"
    }
  },
  {
    "insert": "\n"
  },
  {
    "insert": "JUST A LIST",
    "attributes": {
      "bold": true,
      "color": "#000000",
      "background": "transparent"
    }
  },
  {
    "insert": "\n",
    "attributes": {
      "align": "center"
    }
  },
  {
    "insert": "\n\n",
    "attributes": {
      "list": "ordered"
    }
  },
  {
    "insert": "\n"
  },
  {
    "insert": "New title",
    "attributes": {
      "bold": true,
      "color": "#000000",
      "background": "transparent"
    }
  },
  {
    "insert": "\nIn publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before final copy is available."
  },
  {
    "insert": "\n",
    "attributes": {
      "align": "justify"
    }
  },
  {
    "insert": "\n\n"
  }
]
```

**Current behavior**
Goes crazy and duplicates the text for each available point.

![Screenshot from 2023-03-23 09-26-57](https://user-images.githubusercontent.com/29523682/227145868-ee969d7e-8c92-4f4b-9d95-240308e68dd4.png)

**Expected behavior**
Should look like in the editor.

![Screenshot from 2023-03-23 09-26-49](https://user-images.githubusercontent.com/29523682/227145926-08323995-5278-4b34-8fe5-8984cf19e570.png)

**Comment by psociety** [comment]
Yeah, i wanted to fix it myself, but after taking a look at what quill gives i didn't really see "how can the system understand when the list finishes".

**Comment by nadar** [comment]
Can you please try in composer with `dev-issue-78 as ^3.0`?

**Comment by psociety** [comment]
Much better now!
It only lists 1 out of the 2 points, but it doesn't go crazy adding the content three times:
![Screenshot from 2023-03-23 14-04-37](https://user-images.githubusercontent.com/29523682/227213093-640e74b1-89b5-4b47-9af2-7da4d396c328.png)

**Comment by nadar** [comment]
There you go https://github.com/nadar/quill-delta-parser/releases/tag/3.3.1
