### ISSUE TITLE
Multiple Attributes can not be distinguished

### ISSUE THREAD

**Issue by upcoders** [nadar/quill-delta-parser#82]
**Bug Description**
When **Header** attribute is accompanied by other attributes, it can not be parsed as Heading. 

**Bug reproduce**

Example:
```
     {
         "insert":"Header"
      },
      {
         "attributes":{
            "align":"right",
            "direction":"rtl",
            "header":2
         },
         "insert":"\n"
      },
```

**The expected html output the delta should produce**

Example:

```
<h2 style="direction:rtl; align: right">Header</h2>
```

**Comment by nadar** [comment]
hi @upcoders thanks for creating the issue.

This is an expected behavior, those attributes do not exists (yet) in the Heading Listener => https://github.com/nadar/quill-delta-parser/blob/master/src/listener/Heading.php

You can create a PR if you like, or i will take care of this if i have some time available.

**Comment by nadar** [comment]
@upcoders 

> The expected html output the delta should produce

what is produced instead?

**Comment by nadar** [comment]
I am going to close this issue to maintain a clean issue tracker for the following reasons:

1. Incomplete information (Are there any unanswered questions? Please provide as much information as possible).
2. Lack of recent activity (No further replies).
3. No one has taken up the task (no Pull Request has been received).

If you believe that this issue remains important or if you have additional or updated information, please consider reopening the issue and informing us.
