### ISSUE TITLE
Exception: An unknown alignment "left" has been detected.

### ISSUE THREAD

**Issue by jayeshindianic** [nadar/quill-delta-parser#84]
**Bug Description**
When i try to convert quill delta to html its throw Exception

Exception: An unknown alignment "left" has been detected.

**Bug reproduce**
its happening only when data is empty with left alignment ex:
```[{"insert":"\n", "attributes":{"align": "left"}},{"insert":" \n"}]```

**Comment by nadar** [comment]
hi @jayeshindianic it seems that left is not valid, it must be: ['center', 'right', 'justify'];

https://github.com/nadar/quill-delta-parser/blob/master/src/listener/Align.php#L21

left is like "no alignment", so i would say we should accept this value?

**Comment by nadar** [comment]
You have closed the issue, so i won't change anything, right? :-)

**Comment by jayeshindianic** [comment]
> You have closed the issue, so i won't change anything, right? :-)

I have removed left align button from my editor, but its best if you also allows left alignment in future so it not failed.

**Comment by nadar** [comment]
@jayeshindianic https://github.com/nadar/quill-delta-parser/releases/tag/3.4.1
