### ISSUE TITLE
Parse Quill 2 tables

### ISSUE THREAD

**Issue by CasperNH** [nadar/quill-delta-parser#86]
Do you plan to add the ability to parse tables from Quill version 2?

Basic example of table from Quill version 2:
[{"insert":"1111"},{"attributes":{"table":"row-nffr"},"insert":"\n"},{"insert":"2222"},{"attributes":{"table":"row-nffr"},"insert":"\n"},{"insert":"3333"},{"attributes":{"table":"row-nffr"},"insert":"\n"},{"insert":"4444"},{"attributes":{"table":"row-nffr"},"insert":"\n"},{"insert":"5555"},{"attributes":{"table":"row-nffr"},"insert":"\n"},{"attributes":{"table":"row-3or1"},"insert":"\n\n\n\n\n"},{"attributes":{"table":"true"},"insert":"\n\n\n\n\n"},{"insert":"\nThis text is outside the table.\n"}]

**Comment by nadar** [comment]
is there a doc? could you beautify that code? what is "nffr" and "row-nffr" and "row-3or1"? If its easy to implement, sure why not.

**Comment by nadar** [comment]
i need an official quill delta doc for tables, could not find anything. Post what your json values above would be expected as render.

**Comment by CasperNH** [comment]
Great, thanks for response. :)

I have been working on this and ended up using better-tables-plus, as the output of a regular quill tables seems to break in the first cell.

This version also covers the ability to control the width of each column.

**I made a custom parser for this, which is working. Still having issue on right align.**
[tableparser.txt](https://github.com/nadar/quill-delta-parser/files/14822748/tableparser.txt)

**Example of table structure in Better Tables Plus:**
[better_tables_example.txt](https://github.com/nadar/quill-delta-parser/files/14822757/better_tables_example.txt)

**Comment by nadar** [comment]
but is there an official documentation how the delta for tables look like, so i could take a look? not sure its a good approach to implement a table support for a 3rd party library which is a fork. Maybe, if there is a documentation, we could provided it as "optional plugin" you can enable, and we name it also the same as the 3rd party library.

**Comment by nadar** [comment]
I am going to close this issue to maintain a clean issue tracker for the following reasons:

1. Incomplete information (Are there any unanswered questions? Please provide as much information as possible).
2. Lack of recent activity (No further replies).
3. No one has taken up the task (no Pull Request has been received).

If you believe that this issue remains important or if you have additional or updated information, please consider reopening the issue and informing us.
